services:
  webserver:
    container_name: webserver-http-server
    image: node:latest
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app:ro
    env_file:
      - .env
    command: >
      sh -c "
      npm install -g http-server &&
      http-server . \
      --username ${USERNAME} \
      --password ${PASSWORD} \
      --port ${PORT} \
      ${SILENT:+--silent}  || tail -f /dev/null"
    ports:
      - "2000:2000"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:$PORT"]
      interval: 30s
      timeout: 10s
      retries: 5




